#!/usr/bin/env python3
"""Extract the ATIP-code -> disc-manufacturer catalog to a C include.

The ATIP lead-in code (min:sec:frame, e.g. 97:26:60) pressed into every CD-R's
pregroove identifies its manufacturer; the code->name mapping is a factual
table. cdrecord ships only a restricted subset (Jorg Schilling's "Orange Forum
Embargo" complaint). This compilation is informed by the media catalog in
PlexTools Professional XL (PTPXL.exe .data @ 0x902300, an array of 224-byte
records: name at +0, ATIP {sec,frame} signature cells from +0x64, spiral length
at record+0xDC). The ATIP codes themselves are public facts (published on the
discs and widely catalogued); they should be cross-referenced against public
ATIP databases. Names are reproduced verbatim only as identifying facts.

Validated against known codes: Mitsubishi 97:34:23 (MCC), CMC 97:26:60,
Taiyo Yuden 97:24:xx, Ritek 97:15:xx, TDK 97:15:00.

Usage: gen_media_db.py <path/to/PTPXL.exe> <output.inc>
"""

import struct
import sys

# .data section: VMA 0x8df000 maps to file offset 0x4df000.
DATA_VMA, DATA_FOFF = 0x8DF000, 0x4DF000
TABLE_VMA = 0x902300     # first manufacturer record
STRIDE = 0xE0            # 224-byte fixed record
NAME_MAX = 0x60          # name field width
CELL_LO, CELL_HI, CELL = 0x64, 0xD9, 0x0C  # ATIP {sec,frame,extra} cells

# Cross-referenced supplement: ATIP codes present in cdrecord's diskid.c
# (schily/cdrtools) but not in the PlexTools table. The two catalogues come
# from independent sources and agree on 107 of ~123 codes; these are the
# high-confidence cdrecord-only codes, folded in for the union (names use our
# table's spelling). cdrecord's one remaining unique (97:20:10) is omitted as
# its author flagged it a guess. Nero 2026 (NeroAPIEngine.dll) was checked too
# and adds nothing — the ATIP manufacturer registry is effectively frozen.
CROSSREF_EXTRA = [
    (31,  0, "Ritek"),
    (31, 30, "Grand Advance Technology"),
    (32,  0, "TDK Corporation"),
]


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    blob = open(sys.argv[1], "rb").read()

    def foff(vma: int) -> int:
        return DATA_FOFF + (vma - DATA_VMA)

    def u32(o: int) -> int:
        return struct.unpack_from("<I", blob, o)[0]

    rows = []
    for i in range(128):  # generous upper bound; we stop at the first bad record
        o = foff(TABLE_VMA + i * STRIDE)
        name = blob[o:o + NAME_MAX].split(b"\x00")[0].decode("latin1", "replace")
        if not name or not name[0].isalnum():
            break  # ran past the table into other .data
        codes = []
        for c in range(CELL_LO, CELL_HI, CELL):
            sec, frame = u32(o + c), u32(o + c + 4)
            if sec == 0xFFFFFFFF:
                continue
            if sec <= 59 and frame <= 74:      # plausible ATIP sec:frame
                codes.append((sec, frame))
        for sec, frame in dict.fromkeys(codes):  # de-dup, keep order
            rows.append((name, sec, frame))

    with open(sys.argv[2], "w") as f:
        f.write(
            "/* ATIP manufacturer catalog — generated by tools/gen_media_db.py;"
            " do not edit.\n *\n"
            " * ATIP code (97:SS:FF) -> disc manufacturer. The codes are public\n"
            " * facts pressed into every CD-R pregroove; this compilation is\n"
            " * informed by PlexTools Professional XL and cross-validated against\n"
            " * cdrecord's diskid.c (schily) and Nero 2026. See docs/reference/ATTRIBUTION.md.\n"
            f" * Manufacturers: {len(set(r[0] for r in rows))},"
            f" codes: {len(rows) + len(CROSSREF_EXTRA)}"
            f" ({len(CROSSREF_EXTRA)} cross-referenced from cdrecord).\n"
            " */\n\n"
        )
        have = {(sec, frame) for _, sec, frame in rows}
        for name, sec, frame in rows:
            esc = name.replace("\\", "\\\\").replace('"', '\\"')
            f.write('    { 97, %2d, %2d, "%s" },\n' % (sec, frame, esc))
        f.write("\n    /* cross-referenced from cdrecord diskid.c (union) */\n")
        for sec, frame, name in CROSSREF_EXTRA:
            if (sec, frame) in have:
                continue
            f.write('    { 97, %2d, %2d, "%s" },\n' % (sec, frame, name))

    total = len(rows) + sum(1 for s, fr, _ in CROSSREF_EXTRA if (s, fr) not in
                            {(sec, frame) for _, sec, frame in rows})
    print("%d manufacturers, %d ATIP codes (%d +%d xref) -> %s"
          % (len(set(r[0] for r in rows)), total, len(rows),
             total - len(rows), sys.argv[2]), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
