#!/usr/bin/env python3
"""Convert redumper's offsets.ixx drive read-offset table to a C include.

The table is user-submitted factual data collected by the REDUMP Disc
Preservation Project (redump.org); we convert the facts and attribute the
source in the generated file and the documentation.

Usage: gen_offsets.py <path/to/offsets.ixx> <output.inc>
"""

import re
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2

    src, dst = sys.argv[1], sys.argv[2]
    entry = re.compile(
        r'\{\s*"(?P<vendor>[^"]*)"\s*,\s*"(?P<product>[^"]*)"\s*,'
        r"\s*(?P<offset>[+-]?\d+)\s*\}"
    )

    entries = []
    with open(src, encoding="utf-8") as fp:
        for line in fp:
            m = entry.search(line)
            if m:
                entries.append(
                    (m["vendor"], m["product"], int(m["offset"]))
                )
    if not entries:
        print(f"no entries found in {src}", file=sys.stderr)
        return 1

    with open(dst, "w", encoding="utf-8") as out:
        out.write(
            "/* Drive read-offset table — generated by tools/gen_offsets.py;"
            " do not edit.\n"
            " *\n"
            " * Source data: user-submitted drive offsets collected by the\n"
            " * REDUMP Disc Preservation Project (https://redump.org),\n"
            " * converted from the table shipped with redumper.\n"
            f" * Entries: {len(entries)}\n"
            " */\n\n"
        )
        for vendor, product, offset in entries:
            out.write(f'    {{ "{vendor}", "{product}", {offset:+d} }},\n')
    print(f"{dst}: {len(entries)} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
